# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WzVNRs0DNHNP-XilI7_QfIfpxU1KfXhm
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd


df = pd.read_csv("WHO COVID-19 cases.csv")

romania_data = df[df["Country"] == "Romania"]
print(romania_data)